import pandas as pd
from datetime import date, timedelta
import numpy as np
from nselib import capital_market
from zoneinfo import ZoneInfo
from flask import Flask, render_template_string

app = Flask(__name__)
name_to_index = {"Monday": 0, "Tuesday": 1, "Wednesday": 2, "Thursday": 3, "Friday": 4, "Saturday": 5, "Sunday": 6}
index_to_name = {v: k for k, v in name_to_index.items()}

read_file = pd.read_excel("stocks.xlsx")
current_date = date.today()
day = current_date.weekday()

if day == 0:
    counterday = 3
elif day == 5:
    counterday = 1
else:
    counterday = 1

yesterday = current_date - timedelta(days=counterday)
today = current_date.strftime("%d-%m-%Y")
yesday = yesterday.strftime("%d-%m-%Y")

list_of_stock = read_file.to_dict(orient='records')

result = capital_market.week_52_high_low_report(today)
print(day, current_date, index_to_name.get(day, day))
print(counterday, yesterday, index_to_name.get(counterday, counterday))

# Loop stocks and safely extract numeric close price
for stock in list_of_stock:
    symbol = stock.get('Stock name')
    # parse target price safely
    try:
        targetPrice = float(stock.get('TargetPrice'))
    except Exception:
        print(symbol, 'invalid target price', stock.get('TargetPrice'))
        continue

    result = capital_market.price_volume_data(symbol, period='1D')

    # Try to get the ClosePrice column/series and convert to pandas Series
    try:
        close_series = pd.Series(result['ClosePrice'])
    except Exception:
        # result might be a dict-like without the column
        print(symbol, 'no ClosePrice column', targetPrice, False)
        continue

    # Drop NaNs and ensure we have at least one numeric value
    close_series = close_series.dropna()
    if close_series.empty:
        print(symbol, 'no valid close price', targetPrice, False)
        continue

    # Take the last available close price and convert to float
    try:
        closedPriceFloat = float(close_series.iloc[-1])
    except Exception:
        # If value is a string with commas or stray characters, clean it
        cleaned = str(close_series.iloc[-1]).replace(",", "").strip("[]'\" ")
        try:
            closedPriceFloat = float(cleaned)
        except Exception:
            print(symbol, 'could not parse close price', close_series.iloc[-1])
            continue

    verdict = "Buy" if closedPriceFloat <= targetPrice else "No Buy"
    #print(symbol, index_to_name.get(counterday, counterday), closedPriceFloat, index_to_name.get(day, day), targetPrice, verdict)


    @app.route('/')
    def index():
        # Capture the output you want to display
        python_output = "Hello, world! This text was generated by Python."

        # Define the HTML template as a string
        html_content = """
        <html>
        <head>
            <title>Python Output Page</title>
        </head>
        <body>
            <h1>Output from Python Script</h1>
            <p>{{ output }}</p>
        </body>
        </html>
        """

        # Render the template, passing the python_output as a variable
        return render_template_string(html_content, output=(symbol, index_to_name.get(counterday, counterday), closedPriceFloat, index_to_name.get(day, day), targetPrice, verdict))


    if __name__ == '__main__':
        app.run(debug=True)