from flask import Flask, render_template_string

app = Flask(__name__)


@app.route('/')
def index():
    # Capture the output you want to display
    python_output = "Hello, world! This text was generated by Python."

    # Define the HTML template as a string
    html_content = """
    <html>
    <head>
        <title>Python Output Page</title>
    </head>
    <body>
        <h1>Output from Python Script</h1>
        <p>{{ output }}</p>
    </body>
    </html>
    """

    # Render the template, passing the python_output as a variable
    return render_template_string(html_content, output=python_output)


if __name__ == '__main__':
    app.run(debug=True)